### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by fgysin** [opsless/ms-teams-github-actions#16]
I have a workflow consisting of two jobs. At the end of both jobs I added the following task to notify our teams channel:

```
       - name: Notify Teams channel in case of failure
        uses: opsless/ms-teams-github-actions@main
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
```

Then I pushed a build I knew would fail (in the second job), expecting the `if: failure()` to trigger and notify our Teams channel. The job did actually trigger, but I got the following error:

```
Run opsless/ms-teams-github-actions@main
Error: socket hang up
```
Why socket error? The Teams webhook works fine: when I tested it before / after with a simple `if: always()` statement, the notification went through...
