### ISSUE TITLE
Parameter ''using: node20' is not supported

### ISSUE THREAD

**Issue by ruidiasbraga** [opsless/ms-teams-github-actions#52]
Yesterday I had this working, but now I got a weird error. Something has changed? saw a release 10hours ago.

Download action repository 'actions/setup-node@v2' (SHA:7c12f8017d5436eb855f1ed4399f037a36fbd9e8)
Download action repository 'opsless/ms-teams-github-actions@main' (SHA:5de7e07f9ce5bd9ed322c2649f1387d4256f1084)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load opsless\ms-teams-github-actions\main\action.yml

**Comment by ahanoff** [comment]
hi @ruidiasbraga, are you running this action on Github or Github Enterprise?

**Comment by ahanoff** [comment]
a quick workaround for you will be specify version `0.3.0` which is running on node16, e.g.

```yaml
- name: Send MS Teams Notification
  uses: opsless/ms-teams-github-actions@0.3.0
  if: always()
  with:
    github-token: ${{ github.token }}
    webhook-uri: ${{ env.MS_TEAMS_WEBHOOK_URI }}

```
