### ISSUE TITLE
Add input option to override workflow status (or conclusion)

### ISSUE THREAD

**Issue by fleroux514** [opsless/ms-teams-github-actions#74]
Here is the use-case:

I have a workflow running 2 jobs, and I want to add a 3rd jobs that depends on the previous ones and is executed only if one of them fails:

```
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "Job 2"

  teams_failure_notification:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: ${{ always() && (needs.job1.outcome != 'success' || needs.job2.outcome != 'success') }}
    steps:
	  - name: Notify failure in Teams
	    uses: opsless/ms-teams-github-actions@main
        with:
		  github-token: ${{ github.token }}
		  webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
		  status: failure
```

Currently the action returns `SUCCEEDED` when job1 or job2 fails so I would need to add an input option (ir  `status: failure`) to force a failure instead

**Comment by fleroux514** [comment]
simple workaround is to manually for failure

```
    steps:
      - name: Force failure
        run: |
          exit 1
      - name: Notify failure in Teams
        uses: opsless/ms-teams-github-actions@1.2.1
        if: ${{ always() }}
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_ALERTS_WEBHOOK }}

```
